ARG SPELLBOOK_DOCUMENT_WORKER_BASE_IMAGE=spellbook-document-worker:local
FROM ${SPELLBOOK_DOCUMENT_WORKER_BASE_IMAGE}

USER root
COPY . /usr/local/share/fonts/microsoft-powerpoint/
RUN fc-cache --force \
    && fc-match --format='%{family}|%{style}|%{file}\n' Aptos \
    && fc-match --format='%{family}|%{style}|%{file}\n' Calibri \
    && fc-match --format='%{family}|%{style}|%{file}\n' Cambria \
    && fc-match --format='%{family}|%{style}|%{file}\n' Arial \
    && fc-match --format='%{family}|%{style}|%{file}\n' 'Times New Roman' \
    && fc-match --format='%{family}|%{style}|%{file}\n' 'Trebuchet MS' \
    && fc-match --format='%{family}|%{style}|%{file}\n' '맑은 고딕' \
    && fc-match --format='%{family}|%{style}|%{file}\n' HeadLineA
RUN test "$(find /usr/local/share/fonts/microsoft-powerpoint -type f \
        \( -iname '*.ttf' -o -iname '*.otf' -o -iname '*.ttc' \) | wc -l)" -ge 501 \
    && fc-match --format='%{family}|%{style}' Aptos | grep --fixed-strings 'Aptos|Regular' \
    && fc-match --format='%{family}|%{style}' Calibri | grep --fixed-strings 'Calibri|Regular' \
    && fc-match --format='%{family}|%{style}' Cambria | grep --fixed-strings 'Cambria|Regular' \
    && fc-match --format='%{family}|%{style}' Arial | grep --fixed-strings 'Arial|Regular' \
    && fc-match --format='%{family}|%{style}' 'Times New Roman' | grep --fixed-strings 'Times New Roman|Regular' \
    && fc-match --format='%{family}|%{style}' 'Trebuchet MS' | grep --fixed-strings 'Trebuchet MS|Regular' \
    && fc-match --format='%{family}|%{style}' '맑은 고딕' | grep --fixed-strings '맑은 고딕|Regular' \
    && fc-match --format='%{family}|%{style}' HeadLineA | grep --fixed-strings 'Liberation Sans Narrow|Bold'

USER 1000:1000
