#!/usr/bin/env python3
"""Generate the deterministic public PPTX used by native mutation conformance."""

from __future__ import annotations

import argparse
import datetime as dt
import tempfile
import zipfile
from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.util import Inches, Pt


ZIP_TIMESTAMP = (2026, 1, 1, 0, 0, 0)


def build_fixture(output: Path) -> None:
    presentation = Presentation()
    presentation.slide_width = Inches(13.333333)
    presentation.slide_height = Inches(7.5)
    slide = presentation.slides.add_slide(presentation.slide_layouts[6])

    background = slide.background.fill
    background.solid()
    background.fore_color.rgb = RGBColor(0xF8, 0xFA, 0xFC)

    text_box = slide.shapes.add_textbox(
        Inches(1), Inches(1), Inches(5.5), Inches(0.9)
    )
    text_frame = text_box.text_frame
    text_frame.clear()
    text_frame.word_wrap = False
    run = text_frame.paragraphs[0].add_run()
    run.text = "Spellbook 검증 العربية"
    run.font.name = "Liberation Sans"
    run.font.size = Pt(24)
    run.font.color.rgb = RGBColor(0x11, 0x18, 0x1F)

    shape = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE, Inches(1), Inches(2.2), Inches(3.2), Inches(1.1)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = RGBColor(0x25, 0x63, 0xEB)
    shape.line.color.rgb = RGBColor(0x1E, 0x3A, 0x8A)
    shape.text_frame.clear()

    properties = presentation.core_properties
    properties.title = "Spellbook native mutation conformance"
    properties.subject = "Public synthetic fixture"
    properties.author = "Spellbook contributors"
    properties.last_modified_by = "Spellbook contributors"
    properties.comments = "Generated by scripts/generate-native-conformance-fixture.py"
    properties.created = dt.datetime(2026, 1, 1, tzinfo=dt.UTC)
    properties.modified = dt.datetime(2026, 1, 1, tzinfo=dt.UTC)
    properties.revision = 1

    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(suffix=".pptx") as temporary:
        presentation.save(temporary.name)
        with zipfile.ZipFile(temporary.name, "r") as source:
            entries = [(name, source.read(name)) for name in sorted(source.namelist())]

    with zipfile.ZipFile(
        output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9
    ) as destination:
        for name, data in entries:
            info = zipfile.ZipInfo(name, ZIP_TIMESTAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            destination.writestr(info, data)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "output",
        nargs="?",
        default="eval/public/fixtures/general-native-surface.pptx",
    )
    args = parser.parse_args()
    build_fixture(Path(args.output).resolve())


if __name__ == "__main__":
    main()
