FROM node:22.22.0-bookworm@sha256:20a424ecd1d2064a44e12fe287bf3dae443aab31dc5e0c0cb6c74bef9c78911c

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/debian.sources \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get build-dep -y libreoffice \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        brotli \
        ccache \
        git \
        ninja-build \
        python-is-python3 \
        rsync \
        xz-utils \
    && rm -rf /var/lib/apt/lists/*

ARG EMSDK_COMMIT=3eb3e02dfd10eaa527ba61b89cfcfba13d1c060d
ARG EMSDK_VERSION=3.1.65
ARG EMSCRIPTEN_COMMIT=949ee1d40467b80e90a9fdc67155d443426fef2d
ARG QT_COMMIT=3d440b7787f9b5ba15e5f8bcd7aef39b388f94fa
ARG QTBASE_COMMIT=a320678c85ec8029d5394bcd673d4c208af1de3a

RUN git clone --quiet https://github.com/emscripten-core/emsdk.git /opt/emsdk \
    && git -C /opt/emsdk checkout --quiet "$EMSDK_COMMIT" \
    && test "$(git -C /opt/emsdk rev-parse HEAD)" = "$EMSDK_COMMIT" \
    && /opt/emsdk/emsdk install "$EMSDK_VERSION" \
    && /opt/emsdk/emsdk activate "$EMSDK_VERSION" \
    && rm -rf /opt/emsdk/upstream/emscripten \
    && git clone --quiet https://github.com/allotropia/emscripten.git /opt/emsdk/upstream/emscripten \
    && git -C /opt/emsdk/upstream/emscripten checkout --quiet "$EMSCRIPTEN_COMMIT" \
    && test "$(git -C /opt/emsdk/upstream/emscripten rev-parse HEAD)" = "$EMSCRIPTEN_COMMIT"

RUN useradd --create-home --uid 1000 --shell /bin/bash builder \
    && mkdir -p /opt/qt5 /opt/qt5-install \
    && chown -R builder:builder /opt/emsdk /opt/qt5 /opt/qt5-install

USER builder

RUN git clone --quiet https://github.com/allotropia/qt5.git /opt/qt5 \
    && git -C /opt/qt5 checkout --quiet "$QT_COMMIT" \
    && test "$(git -C /opt/qt5 rev-parse HEAD)" = "$QT_COMMIT" \
    && cd /opt/qt5 \
    && ./init-repository --module-subset=qtbase \
    && git -C qtbase checkout --quiet "$QTBASE_COMMIT" \
    && test "$(git -C qtbase rev-parse HEAD)" = "$QTBASE_COMMIT" \
    && source /opt/emsdk/emsdk_env.sh >/dev/null \
    && ./configure \
        -opensource \
        -confirm-license \
        -xplatform wasm-emscripten \
        -feature-thread \
        -release \
        -nomake examples \
        -nomake tests \
        -no-pch \
        -prefix /opt/qt5-install \
        QMAKE_CFLAGS+=-sSUPPORT_LONGJMP=wasm \
        QMAKE_CXXFLAGS+=-sSUPPORT_LONGJMP=wasm \
    && make -j8 module-qtbase \
    && make -C qtbase install

ENV SPELLBOOK_EMSDK_ENV=/opt/emsdk/emsdk_env.sh
ENV SPELLBOOK_QT5DIR=/opt/qt5-install

WORKDIR /workspace
